Restaurant_Kitchen_Service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("kitchen.urls", namespace="kitchen")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.urls import path

from .views import (
    index,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishCreateView,
    DishListView,
    DishUpdateView,
    DishDeleteView,
    DishDetailView
)

urlpatterns = [
    path("", index, name="index"),
    path("dish_type/",
         DishTypeListView.as_view(),
         name="dish-type-list"),
    path("dish_type/<int:pk>/detail/",
         DishTypeDetailView.as_view(),
         name="dish-type-detail"),
    path("dish_type/create/",
         DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("dish_type/<int:pk>/update/",
         DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("dish_type/<int:pk>/delete/",
         DishTypeDeleteView.as_view(),
         name="dish-type-delete"),
    path("ingredients/",
         IngredientListView.as_view(),
         name="ingredients-list"),
    path("ingredients/create/",
         IngredientCreateView.as_view(),
         name="ingredients-create"),
    path("ingredients/<int:pk>/update/",
         IngredientUpdateView.as_view(),
         name="ingredients-update"),
    path("ingredients/<int:pk>/delete/",
         IngredientDeleteView.as_view(),
         name="ingredients-delete"),
    path("cooks/",
         CookListView.as_view(),
         name="cooks-list"),
    path("cook/<int:pk>/detail/",
         CookDetailView.as_view(),
         name="cook-detail"),
    path("cook/create/",
         CookCreateView.as_view(),
         name="cook-create"),
    path("cook/<int:pk>/update/",
         CookUpdateView.as_view(),
         name="cook-update"),
    path("cook/<int:pk>/delete/",
         CookDeleteView.as_view(),
         name="cook-delete"),
    path("dish/",
         DishListView.as_view(),
         name="dish-list"),
    path("dish/<int:pk>/",
         DishDetailView.as_view(),
         name="dish-detail"),
    path("dish/<int:pk>/update/",
         DishUpdateView.as_view(),
         name="dish-update"),
    path("dish/create/",
         DishCreateView.as_view(),
         name="dish-create"),
    path("dish/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"),
]

app_name = "kitchen"

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Sum
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Ingredients(models.Model):
    name = models.CharField(max_length=255, unique=True)
    ingredient_cost = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    year_of_experience = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    descriptions = models.TextField(default="This is the best dish in the world ")
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dish")
    ingredients = models.ManyToManyField(Ingredients, related_name="dish")

    class Meta:
        verbose_name = "dish"
        verbose_name_plural = "dishes"
        ordering = ["dish_type", "name"]

    def __str__(self):
        return self.name

    @property
    def ingredient_total_cost(self):
        queryset = Dish.objects.filter(
            id=self.id
            ).annotate(
            dish_total_cost=Sum("ingredients__ingredient_cost")
            ).values(
            "dish_total_cost"
        )
        if queryset[0]["dish_total_cost"] is not None:
            return round(queryset[0]["dish_total_cost"], 2)
        else:
            return "No ingredients"


kitchen/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Ingredients, Cook


class SearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class CooksSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class IngredientsForm(forms.ModelForm):
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredients.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Ingredients
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (

            "first_name",
            "last_name",
            "year_of_experience",
        )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import SearchForm, CooksSearchForm, CookCreationForm
from kitchen.models import Dish, DishType, Cook, Ingredients


@login_required
def index(request):
    num_dish = Dish.objects.count()
    num_type_dish = DishType.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dish": num_dish,
        "num_type_dish": num_type_dish,
        "num_cooks": num_cooks
    }
    return render(request, "kitchen/index.html", context=context)


"""Dish Types"""


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type/dish_type_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = SearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    paginate_by = 5
    template_name = "kitchen/dish_type/dish_type_detail.html"


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


"""ingredients"""


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredients
    template_name = "kitchen/ingredients/ingredients_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["ingredients_search_form"] = SearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Ingredients.objects.all()
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredients
    fields = "__all__"
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:ingredients-list")


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredients
    fields = "__all__"
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:ingredients-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredients
    template_name = "kitchen/ingredients/ingredients_confirm_delete.html"
    success_url = reverse_lazy("kitchen:ingredients-list")


"""cooks"""


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5
    template_name = "kitchen/cooks/cooks_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["cooks_search_form"] = CooksSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CooksSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    template_name = "kitchen/cooks/cook_detail.html"


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:cooks-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    fields = "__all__"
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:cooks-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    template_name = "kitchen/cooks/cook_confirm_delete.html"
    success_url = reverse_lazy("kitchen:cooks-list")


"""dishes"""


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    template_name = "kitchen/dishes/dishes_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["dish_search_form"] = SearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    fields = "__all__"
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    template_name = "kitchen/dishes/dish-details.html"


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"
    template_name = "kitchen/create-update_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    template_name = "kitchen/dishes/dish_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")

templates/kitchen/cooks/cook_confirm_delete.html
{% extends "layouts/base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}


  <!-- -------- START HEADER 1 w/ text and image on right ------- -->

  <header>
    <div class="page-header section-height-100">

    <!-------------image--------------------------------------------->

      <div class="oblique position-absolute top-0 h-100 d-md-block d-none">
        <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6"
             style="background-image:url({{ ASSETS_ROOT }}/img/cooks/cook_delete.png);
                     background-size: auto;
                     background-repeat: no-repeat;
                     background-position: center">
        </div>
      </div>
  <!------------------end image------------------------------>
      <!--------------Container ------------------------------>
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
            <h1 class="text-gradient text-primary">Delete cook:</h1>
            <h3>"{{ cook.username }}" ?</h3>
            <!---------------------dynamic content------------------>
            <form action="" method="post">
              {% csrf_token %}
              <input type="submit" value="Yes" class="btn btn-danger">
              <a href="{% url 'kitchen:cook-detail' pk=cook.id %}"
                 class="btn btn-success cancel-link ">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}
<!-- -------- END HEADER 1 w/ text and image on right ------- -->

templates/kitchen/cooks/cook_detail.html
{% extends "layouts/base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}


  <!-- -------- START HEADER 1 w/ text and image on right ------- -->
  <!-------------image--------------------------------------------->
  <header>
    <div class="page-header section-height-100">

      <div class="oblique position-absolute top-0 h-100 d-md-block d-none">
        <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6"
             style="background-image:url({{ ASSETS_ROOT }}/img/cooks/cook_5.jpg);
                     background-size: auto;
                     background-repeat: no-repeat;
                     background-position: center">
        </div>
      </div>
      <!-----------end image----------------------------------->
      <!--------------Container ------------------------------>
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
            <h1 class="text-gradient text-primary">Cook Detail </h1>
            <!------------------dynamic content------------------>
            <h2><strong>Cook username:</strong> {{ cook.username }}
              <div class="btn-group link_to_page">
                <button type="button" class="btn bg-gradient-info "><a
                    href="{% url 'kitchen:cook-update' pk=cook.id %}">update</a>
                </button>
                <button type="button" class="btn bg-gradient-primary"><a
                    href="{% url 'kitchen:cook-delete' pk=cook.id %}">Delete</a>
                </button>
              </div>
            </h2>

            <p><strong>Cooks username:</strong> {{ cook.username }}</p>
            <p><strong>Cooks first name:</strong> {{ cook.first_name }}</p>
            <p><strong>Cooks last name:</strong> {{ cook.last_name }}</p>
            <p><strong>Cooks e-mail:</strong> {{ cook.email }}</p>
            <p><strong>Year of experience:</strong> {{ cook.year_of_experience }}</p>
            <hr>
            <h4>
              Dishes:
            </h4>
            {% if cook.dish.all %}
              <ul>
                {% for dish in cook.dish.all %}
                  <li>{{ dish }}</li>
                {% endfor %}
              </ul>
            {% else %}
              <p>This chef has no dishes. Add them. </p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}
<!-- -------- END HEADER 1 w/ text and image on right ------- -->

templates/kitchen/cooks/cooks_list.html
{% extends "layouts/base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}


  <!-- -------- START HEADER 1 w/ text and image on right ------- -->
  <!-------------image--------------------------------------------->
  <header>
    <div class="page-header section-height-100">

      <div class="oblique position-absolute top-0 h-100 d-md-block d-none">
        <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6"
             style="background-image:url({{ ASSETS_ROOT }}/img/cooks/cook_3.jpg);
                     background-position: center">
        </div>
      </div>
      <!------------end image------------------------->
      <!--------------Container ------------------------------>
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
            <h1 class="text-gradient text-primary">Cooks List </h1>
            <!--------------------Search form-------------------->
            <form action="" method="get" class="input-group ">
              {{ cooks_search_form|crispy }}
              <input type="submit" class="btn btn-secondary search_button " value="🔍">
              <!-------------------end search form-------------------->
              <div class="buttons">
                <button type="button" class="btn bg-gradient-info position-absolute top-0 end-0"><a
                    href="{% url "kitchen:cook-create" %}">Create</a>
                </button>
              </div>
            </form>

            <!------------------dynamic content------------------>
            <div>
              {% if cook_list %}
                <table class="table">
                  <tr>
                    <th>ID</th>
                    <th>Cook username</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Year of experience</th>
                  </tr>

                  {% for cook in cook_list %}
                    <tr>
                      <td>
                        {{ cook.id }}
                      </td>
                      <td>
                        <a href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.username }}</a>
                      </td>
                      <td>
                        {{ cook.first_name }}
                      </td>
                      <td>
                        {{ cook.last_name }}
                      </td>
                      <td>
                        {{ cook.year_of_experience }}
                      </td>
                    </tr>
                  {% endfor %}
                </table>

              {% else %}
                <p>There are no dish types in the service.</p>
              {% endif %}
            </div>
            <!--------pagination---->
            {% block pagination %}
              {% include "includes/pagination.html" %}
            {% endblock %}
            <!-----end pagination------>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}
<!-- -------- END HEADER 1 w/ text and image on right ------- -->