Restaurant_Kitchen_Service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("kitchen.urls", namespace="kitchen")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.urls import path

from .views import (
    index,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishCreateView,
    DishListView,
    DishUpdateView,
    DishDeleteView,
    DishDetailView
)

urlpatterns = [
    path("", index, name="index"),
    path("dish_type/",
         DishTypeListView.as_view(),
         name="dish-type-list"),
    path("dish_type/<int:pk>/detail/",
         DishTypeDetailView.as_view(),
         name="dish-type-detail"),
    path("dish_type/create/",
         DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("dish_type/<int:pk>/update/",
         DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("dish_type/<int:pk>/delete/",
         DishTypeDeleteView.as_view(),
         name="dish-type-delete"),
    path("ingredients/",
         IngredientListView.as_view(),
         name="ingredients-list"),
    path("ingredients/create/",
         IngredientCreateView.as_view(),
         name="ingredients-create"),
    path("ingredients/<int:pk>/update/",
         IngredientUpdateView.as_view(),
         name="ingredients-update"),
    path("ingredients/<int:pk>/delete/",
         IngredientDeleteView.as_view(),
         name="ingredients-delete"),
    path("cooks/",
         CookListView.as_view(),
         name="cooks-list"),
    path("cook/<int:pk>/detail/",
         CookDetailView.as_view(),
         name="cook-detail"),
    path("cook/create/",
         CookCreateView.as_view(),
         name="cook-create"),
    path("cook/<int:pk>/update/",
         CookUpdateView.as_view(),
         name="cook-update"),
    path("cook/<int:pk>/delete/",
         CookDeleteView.as_view(),
         name="cook-delete"),
    path("dish/",
         DishListView.as_view(),
         name="dish-list"),
    path("dish/<int:pk>/",
         DishDetailView.as_view(),
         name="dish-detail"),
    path("dish/<int:pk>/update/",
         DishUpdateView.as_view(),
         name="dish-update"),
    path("dish/create/",
         DishCreateView.as_view(),
         name="dish-create"),
    path("dish/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"),
]

app_name = "kitchen"

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-12 mb-4  text-center">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Restaurant Kitchen Service</h6>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Restaurant Kitchen Service-Coded by Roman Harmatiuk
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation.html
{% load crispy_forms_filters %}
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4"
                style="background: #daf3b9!important;">
        <div class="container-fluid">

          <a class="navbar-brand font-weight-bolder ms-sm-3"
             href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
            Restaurant Kitchen Service
          </a>

          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav  ms-lg-6 ps-lg-2 w-100">

              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'kitchen:dish-type-list' %}">
                  Dish Type
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'kitchen:dish-list' %}">
                  Dish
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'kitchen:cooks-list' %}">
                  Cooks
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'kitchen:ingredients-list' %}">
                  Ingredients
                </a>
              </li>

              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon ps-2" href="{% url 'logout' %}">
                  <i class="fa fa-sign-out me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom" title="Logout">Logout</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}

<section class="py-1">
  <div class="container">
    <div class="row justify-space-between py-2">
      <div class="col-lg-4 mx-auto">
        {% if is_paginated %}
          <ul class="pagination pagination-primary m-4">

             {% if page_obj.has_previous %}
              <li class="page-item">
              <a class="page-link" href="?{% query_transform request page=1 %}">1</a>
              </li>
            {% endif %}

            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}"
                   aria-label="Previous">
                  <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                </a>
              </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
              <li class="page-item">
              <a class="page-link">{{ page_obj.next_page_number }}</a>
              </li>
            {% endif %}

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}"
                   aria-label="Next">
                  <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                </a>
              </li>
            {% endif %}

            {% if page_obj.has_next %}
              <li class="page-item">
              <a class="page-link" href="?{% query_transform request page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
              </li>
            {% endif %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
</section>

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>